"""Altered some columns in match and deleted unused columns in user

Revision ID: 0ecf6406e4ec
Revises: afef553f579a
Create Date: 2026-05-16 12:57:12.921513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecf6406e4ec'
down_revision = 'afef553f579a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('moves',
               existing_type=sa.TEXT(length=8000),
               type_=sa.String(length=8000),
               existing_nullable=False)
        batch_op.alter_column('player',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('opponent',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('player_colour',
               existing_type=sa.TEXT(length=5),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('result',
               existing_type=sa.TEXT(length=20),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('termination',
               existing_type=sa.TEXT(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=100),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(length=256),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lichess_rating', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('chesscom_username', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('lichess_username', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('ratings_last_updated', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('chesscom_rating', sa.INTEGER(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(length=256),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('termination',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=True)
        batch_op.alter_column('player_colour',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(length=5),
               existing_nullable=False)
        batch_op.alter_column('opponent',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('player',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=100),
               existing_nullable=False)
        batch_op.alter_column('moves',
               existing_type=sa.String(length=8000),
               type_=sa.TEXT(length=8000),
               existing_nullable=False)

    # ### end Alembic commands ###
