"""add profile_pic to user

Revision ID: 5df432704226
Revises: 6dfe255fa006
Create Date: 2026-05-10 22:45:40.319846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df432704226'
down_revision = '6dfe255fa006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('player2_color')
        batch_op.drop_column('player1_color')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1_color', sa.VARCHAR(length=5), nullable=False))
        batch_op.add_column(sa.Column('player2_color', sa.VARCHAR(length=5), nullable=False))

    # ### end Alembic commands ###
