"""Add color tracking to Match model

Revision ID: 6dfe255fa006
Revises: 
Create Date: 2026-05-04 14:01:26.841279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfe255fa006'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add nullable columns first (SQLite limitation)
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1_color', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('player2_color', sa.String(length=5), nullable=True))

    # Update existing records with default values
    op.execute("UPDATE match SET player1_color = 'white' WHERE player1_color IS NULL")
    op.execute("UPDATE match SET player2_color = 'black' WHERE player2_color IS NULL")

    # Make columns NOT NULL
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('player1_color', nullable=False)
        batch_op.alter_column('player2_color', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('player2_color')
        batch_op.drop_column('player1_color')

    # ### end Alembic commands ###
