"""Added notes column in Query table

Revision ID: a67570f5a7bf
Revises: 0ecf6406e4ec
Create Date: 2026-05-16 16:02:31.043390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67570f5a7bf'
down_revision = '0ecf6406e4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
