"""Added status to query page

Revision ID: d9fbbc8c6b5d
Revises: b3c4d5e6f7a8
Create Date: 2026-05-15 09:33:08.303427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9fbbc8c6b5d'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint('issue_id', ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_constraint('issue_id', type_='unique')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
