"""Added created_at column

Revision ID: 3201fd6af61c
Revises: 3ce8ad4244ce
Create Date: 2026-05-15 15:35:01.022184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3201fd6af61c'
down_revision = '3ce8ad4244ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
