"""New fields on User table

Revision ID: eb069d3ffe38
Revises: b47e50e0eecb
Create Date: 2026-05-16 22:57:20.816938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb069d3ffe38'
down_revision = 'b47e50e0eecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chesscom_username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('lichess_username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fide_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fide_id')
        batch_op.drop_column('lichess_username')
        batch_op.drop_column('chesscom_username')

    # ### end Alembic commands ###
